#spring:
#  datasource:
#    url: jdbc:h2:mem:car-shop
#    driverClassName: org.h2.Driver
#    username: admin
#    password: admin
#  h2:
#    console:
#      enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carshop
    username: postgres
    password: postgres
